### ISSUE TITLE
Guns on ground arent cleared after/before game

### ISSUE THREAD

**Issue by BearNationSMP** [PugaBear/BearNation#43]
**Noahkiq**: murder issue, title is self-explanatory

**Comment by PugaBear** [comment]
Worked for me, code looks right to me. 

It uses the Minigame Name to find the region named `murder_<name>`, and clears all dropped entities inside that region, activates on StartMinigameEvent and EndMinigameEvent, which are when you are teleported out of the lobby into the map, and when the win message is broadcasted into chat, respectively.

If it happens again, note the time, I'll see if there's errors on console. Reopen this if it happens again
